#启动环境配置
spring:
  profiles:
    active: dev

#引入日志配置文件
#=====================================  log  =============================
logging:
  config: classpath:logback-boot.xml

#自定义配置 在xml中通过springProperty 或者 ${} 取值
#  <springProperty scope="context" name="logdir" source="logback.logdir"/>
#  <contextName>${appname}</contextName>
#logback:
#  logdir: /logtest.txt
#  appname: logtest